{% set name = "pytest-faulthandler" %}
{% set version = "2.0.1" %}
{% set hash_type = "sha256" %}
{% set hash = "ed72bbce87ac344da81eb7d882196a457d4a1026a3da4a57154dacd85cd71ae5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0  
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python    
    - pip
    - setuptools
  run:
    - python
    - pytest >=5.0    

about:
  home: https://github.com/pytest-dev/pytest-faulthandler
  license: MIT
  summary: py.test plugin that activates the fault handler module for tests (dummy package now)

extra:
  recipe-maintainers:
    - nicoddemus
