{% set name = "pytest-faulthandler" %}
{% set version = "1.4.1" %}
{% set hash_type = "sha256" %}
{% set hash = "40136337387bf07f30058e3f970558a96f5539348c2dac7b65602cc77edc71ae" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest

test:
  imports:
    - pytest_faulthandler

about:
  home: https://github.com/pytest-dev/pytest-faulthandler
  license: MIT
  summary: py.test plugin that activates the fault handler module for tests

extra:
  recipe-maintainers:
    - nicoddemus
