{% set name = "pytest-faulthandler" %}
{% set version = "1.3.1" %}
{% set hash_type = "sha256" %}
{% set hash = "bd02b812814db90e19e008f96853996c70064c5a94f84e3db41719543401bcb5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytest
    - setuptools
  run:
    - python
    - pytest

test:
  imports:
    - pytest_faulthandler

about:
  home: https://github.com/pytest-dev/pytest-faulthandler
  license: MIT
  summary: py.test plugin that activates the fault handler module for tests

extra:
  recipe-maintainers:
    - nicoddemus
