appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QFaT5OPKONULI6ZPiLVzW6rWuNEqcrmXftv6P5r7G0ygmj/wxQS40N0A/PS37OfH0QW4j4g0LA8ifUp5XtuR4rUb48inGXj7w8iyrf5ABNUfrojyNX5o/fDmU94yWfGBV/BLbsqMc/Dvw6yWF8GOopLL2ySGzQ6ghfzDdH4BBm4GXCyAOcuuK6muOMFOeFKJXy5yg/4HalyXPL0CHmfRRZjKLWWVwiPyfqIRX7IrDaL/T3+NDAWweEI2zSKsFi5WATQBxgC4WNmLbANeIw/LYK5ozEHA0gemmkCJw9GES/YdY6me5tx2mXF/5U7jJm+QguW1AwwL3iSy51Of5pXlKspNzokUMpxFW1QUEg+u2EQfXmb4iR0WVLefaNhv+5pgqWEiiFTuPrWqONpjwxesslbC4ECB70YpWMlOA8P0gAmPAxOrU3zv+J42zHdrxR4JQfOicwK1Msc38c3YWL3UcKJvpmZf0hxlI/ZGoXpxLRyJAhAyTFTHmU9TPJMHH0+E0Edp2NiokT5Je7Fa8lf4vGFQC8PAMNU01Px4X0dpW2MyMZgEhoa33Gaslea7fW1klu7cOaJp+96Hg1FmuViQ4WX0ewena53kp2z+rg4nbr5f7lwG4E4hpJXpyey7rJLw1CF6f4Lu/j+KOTZKongoFBD18B6Cd3EmepyK/COJYQw=}
