travis:
  secure:
    BINSTAR_TOKEN: C917JljdMye+uAJWXbOYiQmXbgIJL10PbuGHYxbnSgDsd12LeTqgEQd6i6uwZwuADoqn0o1XgE2iA3yCGXJvQ9lQP+HNIrnIJjkHJM9ZYBgCjsTnEM81mpi5w4kdni0pnbPh+Y2vVoqnYzuA5uWmrZMJobDAzEfErJ+sqYWe+p8cmt2nUJao9JS3SlKoRaG4e/PqB4gym3xPg1SHWut2cdxrDZQKfSFkscHQdBa3E6DOhv1Ux1924n6dZIeG2fmaVek3Iz1Hqd+SIjQ/alBE973Q7t4XAoGPE9VBQb6ESUHLwsJlmJjrYMdgVRA7N6NUDtGTD9HVPkKH7/K+A+Zh1FrO+ivsigfzF1l3TGL9yyCyo5scUcWvn+vxk3WWVnUQXEpljcmjaovCljelFayGFms1ySfQUUglYh2bDNetLafDoa1qtO1+Ulp3BEe9MSX1juuUnttaD4T9M3AN5mbNpz7k1OjW20UbaQAw5ODvEGN7uVDFb8z7/0ZtEcq+rTFBBLwO6KznypGhR6M+UtzwJ6psps9UIBkfwsvwnS3zKaLXWBM8DKCr57gVAaosiqL7dsCI2c0iLLnhLU2Ci7Op8MAqd6wFCw0cWV/Ato1G2Kl1et1CIamDfJZ468LEr+O8nP9JdNuASLFEiAlFD1nfeKBfiNVDMpK4cHV8Nqga4gw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
